name: on-issues-labeled
on:
  issues:
    types: ['labeled', 'unlabeled']
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_OWNER: ${{ github.repository_owner }}
  GITHUB_REPO: ${{ github.repository }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - name: Get issue
        env:
          GITHUB_ISSUE_NUMBER: ${{ github.event.issues.issue.number }}
          GITHUB_ISSUE_LABELS: ${{ github.event.issues.issue.labels }}
        run: pnpm single
      - name: Build
        run: pnpm build --base /${{ github.event.repository.name }}/
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vitepress/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1