name: on-issues
on:
  issues:
    types: ['labeled', 'unlabeled', 'edited', 'reopened', 'closed', 'deleted']
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_OWNER: ${{ github.repository_owner }}
  GITHUB_REPO: ${{ github.repository }}
  GITHUB_ISSUE_NUMBER: ${{ github.event.issue.number }}
  GITHUB_ISSUE_LABEL: ${{ github.event.label.name }}
  GITHUB_ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ',') }}
  GITHUB_EVENT_ACTION: ${{ github.event.action }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Cache dependencies and docs
        uses: actions/cache@v3
        id: docs-cache
        with:
          path: |
            node_modules
            docs
          key: ${{ runner.os }}-config-${{ hashFiles('**/config.js') }}-${{ hashFiles('**/sidebar.js') }}-yarn-${{ hashFiles('**/yarn.lock') }} }}
          restore-keys: |
            ${{ runner.os }}-config-
      - name: Install dependencies
        if: steps.docs-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - name: Get issue
        run: yarn single
      - name: Build
        run: yarn build --base /${{ github.event.repository.name }}/
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vitepress/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
