name: on-push

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_OWNER: ${{ github.repository_owner }}
  GITHUB_REPO: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Cache dependencies and docs
        uses: actions/cache@v3
        id: docs-cache
        with:
          path: |
            node_modules
            docs
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }} }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        if: steps.docs-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - name: Get issues
        run: yarn all
      - name: Build
        run: yarn build --base /${{ github.event.repository.name }}/
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vitepress/dist

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
